### ISSUE TITLE
Issue of auto-completion on parent's fields 

### ISSUE THREAD

**Issue by QiuyanLiuXXX** [sf-explorer/documentation#10]
Hello SF explorer team,

For the SOQL search functionality, auto-completion is not working when I try to reference a field at the parent level through a lookup field. Could you please check?

Thank you for your help! 

<img width="361" alt="Capture" src="https://github.com/user-attachments/assets/64b1ed6c-6b74-4471-9ee2-df082c04f89f">

**Comment by nicolas-despres** [comment]
Thanks for your feedback. It should be available on Monday. You will have to use ctrl+space
